import hmac
import hashlib
import html
import uuid
from typing import Optional
from fastapi import HTTPException, Security, status, Header
from fastapi.security import APIKeyHeader
from backend.config import settings

api_key_header = APIKeyHeader(name="X-Admin-Key", auto_error=False)


def generate_session_id() -> str:
    """Generate a secure cryptographically random session identifier."""
    return f"sess_{uuid.uuid4().hex}"


def sanitize_text(text: Optional[str]) -> Optional[str]:
    """Sanitize user input against XSS attacks."""
    if text is None:
        return None
    # Escape dangerous HTML characters
    return html.escape(text.strip())


def verify_razorpay_payment_signature(
    razorpay_order_id: str,
    razorpay_payment_id: str,
    razorpay_signature: str,
    secret: str
) -> bool:
    """
    Verify payment signature generated by Razorpay Checkout.
    Algorithm: HMAC-SHA256(order_id + '|' + payment_id, secret) == signature
    """
    if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature or not secret:
        return False
    
    msg = f"{razorpay_order_id}|{razorpay_payment_id}".encode("utf-8")
    expected_signature = hmac.new(
        secret.encode("utf-8"),
        msg,
        hashlib.sha256
    ).hexdigest()
    
    return hmac.compare_digest(expected_signature, razorpay_signature)


def verify_razorpay_webhook_signature(
    raw_body: bytes,
    received_signature: str,
    webhook_secret: str
) -> bool:
    """
    Verify webhook signature from Razorpay.
    Algorithm: HMAC-SHA256(raw_body, webhook_secret) == X-Razorpay-Signature
    """
    if not raw_body or not received_signature or not webhook_secret:
        return False
        
    expected_signature = hmac.new(
        webhook_secret.encode("utf-8"),
        raw_body,
        hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(expected_signature, received_signature)


def verify_cashfree_webhook_signature(
    timestamp: str,
    raw_body: bytes,
    received_signature: str,
    secret_key: str
) -> bool:
    """
    Verify Cashfree PG Webhook Signature.
    Algorithm: base64(HMAC-SHA256(timestamp + raw_body, secret_key)) == x-webhook-signature
    """
    import base64
    if not timestamp or not raw_body or not received_signature or not secret_key:
        return False
        
    data = timestamp.encode("utf-8") + raw_body
    computed_sig = base64.b64encode(
        hmac.new(secret_key.encode("utf-8"), data, hashlib.sha256).digest()
    ).decode("utf-8")
    
    return hmac.compare_digest(computed_sig, received_signature)


async def get_admin_auth(x_admin_key: Optional[str] = Security(api_key_header)) -> bool:
    """Dependency to enforce Admin API Key security."""
    if not x_admin_key or not hmac.compare_digest(x_admin_key, settings.ADMIN_SECRET_KEY):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or missing Admin API Key (X-Admin-Key)",
            headers={"WWW-Authenticate": "ApiKey"},
        )
    return True
